const data = [
  {
    id: 1,
    movie: 'They Live',
    genre: ['Action', 'Horror', 'SciFi'],
    year: 1988,
    price: '£10.00',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 2,
    movie: 'Lost In Translation',
    genre: ['Comedy', 'Drama'],
    year: 2003,
    price: '£9.65',
    ultraHD: false,
    stock: 7,
  },
  {
    id: 3,
    movie: 'Man With A Movie Camera',
    genre: ['Documentary', 'Music'],
    year: 1929,
    price: '£20.22',
    ultraHD: true,
    stock: 3,
  },
  {
    id: 4,
    movie: 'The Fog',
    genre: ['Horror', 'Thriller'],
    year: 1980,
    price: '£8.09',
    ultraHD: true,
    stock: 4,
  },
  {
    id: 5,
    movie: 'The Thing',
    genre: ['Horror', 'Mystery', 'SciFi'],
    year: 1982,
    price: '£19.65',
    ultraHD: true,
    stock: 0,
  },
  {
    id: 6,
    movie: 'Interstellar',
    genre: ['Adventure', 'Drama', 'SciFi'],
    year: 2014,
    price: '£20.22',
    ultraHD: true,
    stock: 32,
  },
  {
    id: 7,
    movie: 'Westworld',
    genre: ['Action', 'SciFi', 'Thriller'],
    year: 1973,
    price: '£15.09',
    ultraHD: true,
    stock: 4,
  },
  {
    id: 8,
    movie: 'Shawhank Redemption',
    genre: ['Drama'],
    year: 1994,
    price: '£13.65',
    ultraHD: false,
    stock: 4,
  },
  {
    id: 9,
    movie: 'The Godfather',
    genre: ['Crime', 'Drama'],
    year: 1972,
    price: '£20.00',
    ultraHD: true,
    stock: 23,
  },
  {
    id: 10,
    movie: 'The Dark Knight',
    genre: ['Drama', 'Action', 'Crime'],
    year: 2008,
    price: '£16.09',
    ultraHD: true,
    stock: 9,
  },
  {
    id: 11,
    movie: 'Pulp Fiction',
    genre: ['Crime', 'Drama'],
    year: 1995,
    price: '£9.65',
    ultraHD: true,
    stock: 5,
  },
  {
    id: 12,
    movie: 'The Good, The Bad and The Ugly',
    genre: ['Adventure', 'Western'],
    year: 1966,
    price: '£18.22',
    ultraHD: false,
    stock: 3,
  },
  {
    id: 13,
    movie: 'Fight Club',
    genre: ['Drama'],
    year: 1999,
    price: '£10.49',
    ultraHD: true,
    stock: 8,
  },
  {
    id: 14,
    movie: 'Inception',
    genre: ['Action', 'Adventure', 'SciFi'],
    year: 2010,
    price: '£12.65',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 15,
    movie: 'The Matrix',
    genre: ['Action', 'SciFi'],
    year: 1999,
    price: '£17.22',
    ultraHD: false,
    stock: 0,
  },
  {
    id: 16,
    movie: 'Se7en',
    genre: ['Crime', 'Drama', 'Mystery'],
    year: 1995,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 17,
    movie: 'City of God',
    genre: ['Crime', 'Drama'],
    year: 2002,
    price: '£4.65',
    ultraHD: false,
    stock: 3,
  },
  {
    id: 18,
    movie: 'Spirited Away',
    genre: ['Animation', 'Adventure', 'Family'],
    year: 2001,
    price: '£20.22',
    ultraHD: false,
    stock: 23,
  },
  {
    id: 19,
    movie: 'The Lion King',
    genre: ['Animation', 'Family'],
    year: 1994,
    price: '£14.09',
    ultraHD: true,
    stock: 5,
  },
  {
    id: 20,
    movie: 'Whiplash',
    genre: ['Drama', 'Music'],
    year: 2014,
    price: '£16.65',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 21,
    movie: 'Harakiri',
    genre: ['Action', 'Drama', 'Mystery'],
    year: 1962,
    price: '£7.22',
    ultraHD: false,
    stock: 3,
  },
  {
    id: 22,
    movie: 'Rear Window',
    genre: ['Thriller', 'Mystery'],
    year: 1954,
    price: '£10.09',
    ultraHD: true,
    stock: 5,
  },
  {
    id: 23,
    movie: 'Alien',
    genre: ['Horror', 'SciFi'],
    year: 1979,
    price: '£14.65',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 24,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 25,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 26,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 27,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 28,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 29,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 30,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 31,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 32,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 33,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 34,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 35,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 36,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 37,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 38,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 39,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 40,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 41,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 42,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 43,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 44,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 45,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 46,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 47,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
  {
    id: 48,
    movie: 'Thieves (Voleurs, Les)',
    genre: ['Crime', 'Drama', 'Romance'],
    year: 1995,
    price: '£2.22',
    ultraHD: false,
    stock: 13,
  },
  {
    id: 49,
    movie: 'Eat',
    genre: ['Drama'],
    year: 2000,
    price: '£12.09',
    ultraHD: true,
    stock: 11,
  },
  {
    id: 50,
    movie: 'Paranormal Activity 2',
    genre: ['Horror', 'IMAX'],
    year: 1986,
    price: '£9.65',
    ultraHD: false,
    stock: 11,
  },
];

/*let images = document.querySelectorAll('img');

for (let [key, value] of Object.entries(images)) {
  console.log(key, value);
  value.addEventListener('click', (e) => {
    data.map((filmitem) => {
      if (e.target.id == filmitem.id) {
        console.log(filmitem);
        let soloimg = document.getElementById(filmitem.id);

        let text = document.createElement('p');
        text = `
            ${filmitem.movie}
            ${filmitem.genre}
            `;
        text.id = filmitem.id;
        soloimg.replaceWith(text);
        console.log(soloimg);

        console.log(e.target.src);
        setTimeout(() => {
          let imgrtn = document.createElement('img');
          imgrtn.src = e.target.src;
          console.log(soloimg);
          soloimg.replaceWith(imgrtn);
        }, 5000);
      }
    });
  });
}*/
